# Credit Crad Fraud Detection
- 28 PCA extracted features + 3 addl.
- Performed Logistic Regression, KNN, Deccison Tree, SVM
- Best model is Logistic Regression

### Install Dependencies

In [240]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [241]:
data=pd.read_csv(r'C:\Users\sriti\Downloads\credit_card_data\creditcard.csv')

In [242]:
data.sample(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5826,6297.0,-1.029435,0.302633,2.634051,0.068429,-0.364914,0.636779,-0.148769,0.203269,1.025685,...,0.066387,0.640891,-0.021607,0.091438,0.002367,1.209814,-0.073966,0.027302,54.00,0
112696,72767.0,-0.942442,1.456096,0.945670,-0.131286,-0.278830,-0.770101,0.308177,0.409716,-0.309947,...,-0.242943,-0.714043,-0.000600,-0.005740,-0.079905,0.101376,0.243781,0.114407,1.98,0
60844,49528.0,1.140780,-0.120445,0.692434,1.328811,-0.358550,0.527287,-0.403303,0.210628,1.010210,...,-0.114859,0.018532,-0.139855,-0.408833,0.674290,-0.242453,0.070543,0.018279,16.94,0
130165,79298.0,-1.251861,-4.234039,-0.672257,1.031242,-1.716559,0.941604,0.998399,0.042770,0.310186,...,0.774317,-0.414845,-1.023385,-0.160807,-0.381181,0.926792,-0.263682,0.204051,1234.03,0
35743,38242.0,0.693744,-0.643068,0.475474,1.454623,-0.576425,0.326848,-0.014558,0.215119,0.295230,...,-0.074386,-0.572288,-0.114056,-0.022102,0.275464,-0.535655,0.004810,0.049279,219.00,0

In [243]:
data.shape

(284807, 31)

### Drop column - Time

In [244]:
data=data.drop(columns=['Time'])

In [245]:
data

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,0.090794,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,-0.166974,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,0.207643,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,-0.054952,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,0.753074,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,4.356170,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,-0.975926,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,-0.484782,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,-0.399126,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,-0.915427,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Unbalanced dataset
    - 0 class > 1 class

In [246]:
data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [247]:
legit=data[data['Class']==0]
fraud=data[data['Class']==1]

In [248]:
print(legit.shape)
print(fraud.shape)

(284315, 30)
(492, 30)

In [249]:
legit.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,...,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.000000,284315.0
mean,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,0.009824,...,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022,0.0
std,1.929814,1.636146,1.459429,1.399333,1.356952,1.329913,1.178812,1.161283,1.089372,1.044204,...,0.716743,0.723668,0.621541,0.605776,0.520673,0.482241,0.399847,0.329570,250.105092,0.0
min,-56.407510,-72.715728,-48.325589,-5.683171,-113.743307,-26.160506,-31.764946,-73.216718,-6.290730,-14.741096,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.604551,-22.565679,-15.430084,0.000000,0.0
25%,-0.917544,-0.599473,-0.884541,-0.850077,-0.689398,-0.766847,-0.551442,-0.208633,-0.640412,-0.532880,...,-0.228509,-0.542403,-0.161702,-0.354425,-0.317145,-0.327074,-0.070852,-0.052950,5.650000,0.0
50%,0.020023,0.064070,0.182158,-0.022405,-0.053457,-0.273123,0.041138,0.022041,-0.049964,-0.091872,...,-0.029821,0.006736,-0.011147,0.041082,0.016417,-0.052227,0.001230,0.011199,22.000000,0.0
75%,1.316218,0.800446,1.028372,0.737624,0.612181,0.399619,0.571019,0.326200,0.598230,0.455135,...,0.185626,0.528407,0.147522,0.439869,0.350594,0.240671,0.090573,0.077962,77.050000,0.0
max,2.454930,18.902453,9.382558,16.875344,34.801666,73.301626,120.589494,18.709255,15.594995,23.745136,...,22.614889,10.503090,22.528412,4.584549,7.519589,3.517346,31.612198,33.847808,25691.160000,0.0

In [250]:
data.groupby(by='Class').mean()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,0.009824,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,-5.676883,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

### Balanced Dataset
    - 0 and 1 class - > 492 features each

In [251]:
legit=legit.sample(n=fraud.shape[0])

In [252]:
new_data=pd.concat([legit,fraud],axis=0)

In [253]:
new_data.describe()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,...,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,-2.356836,1.781422,-3.490222,2.274953,-1.585337,-0.711740,-2.771731,0.290199,-1.299625,-2.829632,...,0.345484,-0.008447,-0.018205,-0.044119,0.001147,0.028239,0.094375,0.039371,106.362988,0.500000
std,5.527083,3.735716,6.236144,3.193943,4.280229,1.796536,5.903477,4.859505,2.322734,4.565052,...,2.777780,1.155513,1.155396,0.557709,0.675026,0.480538,1.020312,0.443259,293.862267,0.500254
min,-30.552380,-11.389081,-31.103685,-3.765427,-25.025820,-7.204195,-43.557242,-41.044261,-13.434066,-24.588262,...,-22.797604,-8.887017,-19.254328,-2.028024,-4.781606,-1.153076,-7.263482,-3.696616,0.000000,0.000000
25%,-2.847766,-0.161966,-5.127094,-0.145102,-1.746270,-1.572363,-3.103817,-0.195695,-2.294075,-4.599841,...,-0.174655,-0.533764,-0.221817,-0.403145,-0.347712,-0.298085,-0.058749,-0.050001,1.500000,0.000000
50%,-0.697008,0.954205,-1.224416,1.307692,-0.446264,-0.637894,-0.621222,0.135480,-0.691365,-0.853764,...,0.150818,-0.024170,-0.030676,0.012470,0.036611,-0.028757,0.060625,0.039858,15.000000,0.500000
75%,1.050686,2.807014,0.358527,4.235631,0.433431,0.043700,0.253810,0.861662,0.170075,0.042382,...,0.652748,0.554303,0.194335,0.376718,0.387618,0.328940,0.452145,0.218829,99.990000,1.000000
max,2.349618,22.057729,3.362225,12.114672,13.349086,14.570654,23.190971,20.007208,7.937413,12.246897,...,27.202839,8.361985,5.466230,3.502385,2.208209,2.745261,4.347262,2.350522,5446.070000,1.000000

In [254]:
new_data['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

### Model Select and Evaluation
    - Performed classifcation by using LR,KNN,DT,SVM

In [255]:
X=new_data.drop(columns='Class',axis=1)
Y=new_data['Class']

In [256]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

### Scaling

In [257]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [258]:
X_train_scaled=scaler.transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [259]:
m1=LogisticRegression()
m2=svm.SVC(kernel='linear',C=10)
m3=DecisionTreeClassifier(max_depth=7)
m4=KNeighborsClassifier(n_neighbors=3)

In [260]:
m1.fit(X_train_scaled,Y_train)
m2.fit(X_train_scaled,Y_train)
m3.fit(X_train_scaled,Y_train)
m4.fit(X_train_scaled,Y_train)

KNeighborsClassifier(n_neighbors=3)

### Results
    - LR performed had decent training and testing accuracy
    - SVM and LR are similar
    - DT has overfitting issues, used h.p to reduced
    - KNN performs low on test dataset

In [261]:
models=[m1,m2,m3,m4]
for model in models:
    X_train_pred=model.predict(X_train_scaled)
    training_accuracy=accuracy_score(X_train_pred,Y_train)
    X_test_pred=model.predict(X_test_scaled)
    test_accuracy=accuracy_score(X_test_pred,Y_test)
    print('{} \nTraining:{} Testing:{}\n'.format(model,training_accuracy,test_accuracy))

LogisticRegression()
Training:0.9466327827191868 Testing:0.9238578680203046

SVC(C=10, kernel='linear')
Training:0.9491740787801779 Testing:0.9289340101522843

DecisionTreeClassifier(max_depth=7)
Training:0.9936467598475223 Testing:0.8934010152284264

KNeighborsClassifier(n_neighbors=3)
Training:0.951715374841169 Testing:0.9086294416243654